import { Construct } from "constructs";
import { Fn, Token, LocalBackend, TerraformStack } from "cdktf";
/*
 * Provider bindings are generated by running `cdktf get`.
 * See https://cdk.tf/provider-generation for more details.
 */
import { HelmProvider } from "./.gen/providers/helm/provider";
import { Release } from "./.gen/providers/helm/release";
import { Namespace } from "./.gen/providers/kubernetes/namespace";
import { KubernetesProvider } from "./.gen/providers/kubernetes/provider";
import { Secret } from "./.gen/providers/kubernetes/secret";
import * as SelfSignedCert from "./.gen/modules/modules/self-signed-cert";

export interface ClusterStackProps {
  clusterName?: string;
  clusterState?: string;
  env?: string;
  kubeconfig?: string;
  helmValues?: string;
  secretsPath?: string;
}

export class ClusterStack extends TerraformStack {
  constructor(scope: Construct, name: string, props: ClusterStackProps = {}) {
    super(scope, name);
    new LocalBackend(this, {
      path: props.clusterState,
    });

    const clusterName = props.clusterName || "cluster1";
    const kubeconfig = props.kubeconfig || "~/.kube/cluster1_config";

    const sshKey = new SelfSignedCert.SelfSignedCert(this, "ssh_key", {
      name: clusterName,
      rootPath: Fn.pathexpand(props.secretsPath || "~/.kube"),
    });
    const argocdNamespace = new Namespace(this, "argocd", {
      metadata: {
        name: "argocd",
      },
    });
    new Secret(this, "argocd_ssh_key", {
      data: {
        "ssh-privatekey": Token.asString(sshKey.privateKeyPemOutput),
        "ssh-publickey": Token.asString(sshKey.publicKeyPathOutput),
      },
      dependsOn: [sshKey, argocdNamespace],
      metadata: {
        name: "argocd-ssh-key",
        namespace: "argocd",
      },
      type: "kubernetes.io/ssh-auth",
    });
    new HelmProvider(this, "helm", {
      kubernetes: {
        configPath: Token.asString(Fn.pathexpand(kubeconfig)),
      },
    });
    new KubernetesProvider(this, "kubernetes", {
      configPath: Token.asString(Fn.pathexpand(kubeconfig)),
    });
    const helmReleaseArgocd = new Release(this, "argocd_8", {
      chart: "argo-cd",
      createNamespace: false,
      dependsOn: [argocdNamespace],
      description: "ArgoCD Helm Chart",
      name: "argo",
      namespace: "argocd",
      repository: "https://argoproj.github.io/argo-helm",
      upgradeInstall: true,
      values: [
        Token.asString(
          Fn.templatefile("../../../cluster1/config.yml", {
            argocd_server_url: "https://argocd-server.argocd.svc.cluster.local",
          })
        ),
      ],
      wait: false,
    });
    helmReleaseArgocd.overrideLogicalId("argocd");
  }
}
